# Set up the Netlify CMS to use the Git Gateway for authentication

backend:
  name: git-gateway
  repo: dmcdaniel90/saxcoderblog
  branch: main
  squash_merges: true

# Setting the publish mode to editorial workflow
publish_mode: editorial_workflow

# Path: public/admin/
media_folder: 'public/' # Media files will be stored in the repo under uploads
public_folder: '/' # Media files will be served from the repo under /uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', optional: true }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
      - {
          label: 'Updated Date',
          name: 'updatedDate',
          widget: 'datetime',
          optional: true,
        }
      - {
          label: 'Is Featured',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          summary: '{{fields.tag}}',
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - {
          label: 'SEO',
          name: 'seo',
          widget: 'object',
          fields:
            [
              {
                label: 'Image',
                name: 'image',
                widget: 'object',
                fields:
                  [
                    { label: 'Source', name: 'src', widget: 'string' },
                    { label: 'Alt Text', name: 'alt', widget: 'string' },
                  ],
              },
            ],
        }
  - name: 'pages'
    label: 'Pages'
    folder: 'src/content/pages'
    create: true
    slug: '{{slug}}'
    media_folder: ''
    public_folder: ''
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
