# Set up the Netlify CMS to use the Git Gateway for authentication

backend:
  name: git-gateway
  repo: dmcdaniel90/saxcoderblog
  branch: main

# Path: public/admin/
media_folder: 'public/' # Media files will be stored in the repo under uploads
public_folder: '/' # Media files will be served from the repo under /uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/content/blog'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string', optional: true }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime' }
      - {
          label: 'Updated Date',
          name: 'updatedDate',
          widget: 'datetime',
          optional: true,
        }
      - {
          label: 'Is Featured',
          name: 'isFeatured',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Content', name: 'content', widget: 'markdown' }
      - label: 'SEO'
        name: 'seo'
        widget: 'object'
        fields:
          - label: 'Image'
            name: 'image'
            widget: 'image'
            fields:
              - label: 'Src'
                name: 'src'
                widget: 'string'
              - label: 'Alt'
                name: 'alt'
                widget: 'string'
